// Generated by CoffeeScript 1.6.3
(function() {
  var makeThumbs, template_thumb;
  template_thumb = $('#template-thumb').html();
  makeThumbs = function(item) {
    var i, img, name, tags, _i, _len;
    name = item['name'];
    img = item['img'];
    tags = '';
    for (_i = 0, _len = img.length; _i < _len; _i++) {
      i = img[_i];
      tags += template_thumb.replace('<%= href %>', i['href']).replace('<%= alt %>', name).replace('<%= src %>', i['src']);
    }
    return tags;
  };
  $.ajax({
    url: 'proxy.php',
    dataType: 'json',
    success: function(ret) {
      var html, item, _i, _len;
      html = '';
      for (_i = 0, _len = ret.length; _i < _len; _i++) {
        item = ret[_i];
        html += makeThumbs(item);
      }
      $('#loading').hide();
      $('body').append(html);
    }
  });
})();
